CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    age int,
    email varchar(100)
);

INSERT INTO Person(name, age, email) VALUES('Tom', 19, 'tom@mail.ru');
INSERT INTO Person(name, age, email) VALUES('Alex', 30, 'alex@mail.ru');
INSERT INTO Person(name, age, email) VALUES('Bob', 27, 'bob@mail.ru');

SELECT * FROM Person;